version: 2
jobs:
  lint:
    docker:
      - image: pryx/goldenegg:latest

    working_directory: ~/places-ar

    steps:
      - checkout
      - run: 
          name: Lint
          command: make lint

workflows:
  version: 2
  build_and_test:
    jobs:

      - lint
