version: 2
jobs:
  lint:
    docker:
      - image: pryx/goldenegg:latest

    working_directory: ~/places-ar

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}  
           
      - run: 
          name: Install depedencies
          command: make setup

      - run: 
          name: Lint
          command: make lint
          
      - run: 
          name: Run tests
          command: make test

      - run: 
          name: Deploy
          command: make deploy PLACES_AR_CREDENTIALS="$PLACES_AR_CREDENTIALS" PLACES_AR_DEPLOY="$PLACES_AR_DEPLOY"

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:

      - lint
